# Generated by Django 2.2.4 on 2020-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_ratings',
            field=models.IntegerField(default=2),
        ),
    ]
