# Generated by Django 2.2.4 on 2020-05-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_place_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_ratings',
            field=models.IntegerField(null=True),
        ),
    ]
