# Generated by Django 2.2.4 on 2020-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200517_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_ratings',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
