# Generated by Django 2.2.4 on 2020-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200517_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
