# Generated by Django 2.2.4 on 2020-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_places_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_description',
            field=models.TextField(default='Please add description', max_length=50),
        ),
        migrations.AlterField(
            model_name='places',
            name='place_name',
            field=models.TextField(default='Please add name', max_length=100),
        ),
    ]
