# Generated by Django 2.2.4 on 2020-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200517_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_image',
            field=models.ImageField(default='images/Varanasi-River-Gange', upload_to='images/'),
        ),
    ]
