# Generated by Django 2.2.4 on 2020-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200517_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_description',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='places',
            name='place_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='place_ratings',
            field=models.IntegerField(default='', null=True),
        ),
    ]
