# Generated by Django 2.2.4 on 2020-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200517_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_image',
            field=models.ImageField(default='images/Varanasi-River-Gange', upload_to='images/images/'),
        ),
    ]
