# Generated by Django 2.2.4 on 2020-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20200524_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_image',
            field=models.ImageField(default='', upload_to='images/images/'),
        ),
    ]
